export const UI_STRINGS = {
  ko: {
    home: "국가",
    checklist: "체크리스트",
    ai: "짐싸기 AI",
    settings: "설정",
    back: "뒤로",
    exploreWorld: "탐험하기",
    whereTo: "어디로\n떠나시나요?",
    regionSelectDesc: "날씨·환율·전압·입국절차 정보를 실시간으로 확인하세요",
    weather: "날씨",
    exchangeVoltage: "환율·전압",
    entryProcedure: "입국절차",
    currentWeather: "현재 날씨",
    weeklyForecast: "주간 예보",
    voltageLabel: "사용 전압",
    currencyLabel: "현지 통화",
    loadingExchange: "환율 정보 로딩 중...",
    visaFree: "무비자",
    visaRequired: "사전 허가 필요",
    koreanPassport: "한국 여권 기준",
    officialSite: "공식 사이트 연결",
    reset: "초기화",
    resetConfirm: "초기화할까요?",
    totalProgress: "전체 진행률",
    packingList: "패킹 리스트",
    addCategoryItem: "+ 항목 추가",
    enterItem: "항목을 입력하세요...",
    add: "추가",
    aiTitle: "짐싸기 AI",
    aiSub: "최종 점검 & AI 조언",
    aiDesc: "짐을 다 싸셨나요? 카메라로 사진을 찍으면 AI의 도움을 받을 수 있습니다.",
    aiStart: "AI 스마트 점검 시작",
    aiReport: "AI 분석 리포트",
    aiAnalyzing: "이미지를 꼼꼼하게 대조 중입니다...",
    aiMissingItems: "! 누락 품목 의심 리스트",
    aiPerfect: "완벽한 준비!",
    aiPerfectDesc: "AI가 분석한 결과, 모든 품목이 잘 챙겨진 것 같습니다.",
    aiExpertAdvice: "전문가의 조언",
    confirm: "확인",
    preferences: "PREFERENCES",
    language: "언어",
    languageDesc: "표시 언어를 선택하세요",
    pushNotif: "푸시 알림",
    pushNotifDesc: "출발 전 체크리스트 알림",
    autoDark: "다크 모드 켜기",
    autoDarkDesc: "어두운 화면으로 사용합니다.",
    themeLight: "밝음",
    themeDark: "어두움",
    themeAuto: "자동",
    notifFeedback: "알림 및 피드백",
    notificationFeedback: "알림 및 피드백",
    aiSmartPacking: "스마트 짐싸기",
    aiAnalysisFailed: "분석에 실패했습니다. 다시 시도해 주세요.",
    appInfo: "앱 정보",
    version: "버전",
    developer: "개발자",
    contact: "문의",
    visitedCountries: "방문한 나라",
    explorer: "여행자",
    days: "일",
    asia: "아시아",
    europe: "유럽",
    na: "북미",
    oceania: "대양주"
  },
  en: {
    home: "Stats",
    checklist: "Checklist",
    ai: "Packing AI",
    settings: "Settings",
    back: "Back",
    exploreWorld: "EXPLORE THE WORLD",
    whereTo: "Where are\nyou going?",
    regionSelectDesc: "Check live weather, rates, voltage, and entry rules info",
    weather: "Weather",
    exchangeVoltage: "Money·Power",
    entryProcedure: "Entry",
    currentWeather: "Current Weather",
    weeklyForecast: "Weekly Forecast",
    voltageLabel: "Voltage",
    currencyLabel: "Currency",
    loadingExchange: "Loading rates...",
    visaFree: "Visa Free",
    visaRequired: "Visa Required",
    koreanPassport: "For Korean Passport",
    officialSite: "Official Site",
    reset: "Reset",
    resetConfirm: "Are you sure you want to reset?",
    totalProgress: "Total Progress",
    packingList: "PACKING LIST",
    addCategoryItem: "+ Add Item",
    enterItem: "Enter item name...",
    add: "Add",
    aiTitle: "Packing AI",
    aiSub: "Final Check & AI Advice",
    aiDesc: "Finished packing? Take a photo, and the AI will help you check everything.",
    aiStart: "Start AI Smart Check",
    aiReport: "AI Analysis Report",
    aiAnalyzing: "Analyzing your luggage image...",
    aiMissingItems: "! Potentially Missing Items",
    aiPerfect: "Perfectly Prepared!",
    aiPerfectDesc: "AI analyzed your image and everything seems to be packed.",
    aiExpertAdvice: "Expert Advice",
    confirm: "Confirm",
    preferences: "PREFERENCES",
    language: "Language",
    languageDesc: "Select your display language",
    pushNotif: "Push Notifications",
    pushNotifDesc: "Checklist reminders before departure",
    autoDark: "Enable Dark Mode",
    autoDarkDesc: "Use dark theme for your eyes.",
    themeLight: "Light",
    themeDark: "Dark",
    themeAuto: "Auto",
    notifFeedback: "Notifications & Feedback",
    notificationFeedback: "Notifications & Feedback",
    aiSmartPacking: "Smart Packing",
    aiAnalysisFailed: "Analysis failed. Please try again.",
    appInfo: "App Info",
    version: "Version",
    developer: "Developer",
    contact: "Contact",
    visitedCountries: "Countries Visited",
    explorer: "Traveler",
    days: "days",
    asia: "Asia",
    europe: "Europe",
    na: "North Am.",
    oceania: "Oceania"
  }
};

export const REGIONS = [
  { 
    id: "asia",   
    emoji: "🏯", 
    label: "아시아", 
    labelEn: "Asia", 
    desc: "13개국", 
    descEn: "13 Countries", 
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=800&auto=format&fit=crop", 
    accent: "#FF6B9D" 
  },
  { 
    id: "europe", 
    emoji: "🏰", 
    label: "유럽",   
    labelEn: "Europe", 
    desc: "8개국",  
    descEn: "8 Countries",  
    imageUrl: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=800&auto=format&fit=crop", 
    accent: "#A855F7" 
  },
  { 
    id: "na",     
    emoji: "🗽", 
    label: "북미",   
    labelEn: "North Am.", 
    desc: "3개국",  
    descEn: "3 Countries",  
    imageUrl: "https://images.unsplash.com/photo-1485738422979-f5c462d49f74?q=80&w=800&auto=format&fit=crop", 
    accent: "#3399FF" 
  },
  { 
    id: "oceania", 
    emoji: "🦘", 
    label: "대양주", 
    labelEn: "Oceania", 
    desc: "2개국",  
    descEn: "2 Countries",  
    imageUrl: "https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?q=80&w=800&auto=format&fit=crop", 
    accent: "#00BBDD" 
  },
];

export const COUNTRIES = [
  { 
    id: "jp", 
    name: "일본", 
    nameEn: "Japan", 
    region: "asia", 
    accent: "#FF6B9D", 
    imageUrl: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=800&auto=format&fit=crop",
    capital: "도쿄", 
    capitalEn: "Tokyo", 
    timezone: "UTC+9", 
    desc: "벚꽃과 사무라이의 나라", 
    descEn: "Land of Cherry Blossoms", 
    weatherIcon: "⛅", 
    weatherSummary: "대부분 맑음. 낮 기온 18-22도 예상. 야외 활동하기 좋은 날씨입니다.", 
    weatherSummaryEn: "Mostly sunny. 18-22°C. Great weather for outdoor activities.", 
    week: [{ d: "월", i: "☀️", t: 21 }, { d: "화", i: "☀️", t: 22 }, { d: "수", i: "⛅", t: 19 }, { d: "목", i: "🌧", t: 18 }, { d: "금", i: "⛅", t: 20 }, { d: "토", i: "☀️", t: 23 }, { d: "일", i: "☀️", t: 22 }], 
    voltage: "100V", 
    voltageType: "Type A (2-pin)", 
    currency: "엔", 
    currencyEn: "Yen", 
    currencySymbol: "¥", 
    currencyCode: "JPY", 
    entry: "Visit Japan Web을 통해 검역, 입국심사, 세관 신고를 미리 등록하세요.", 
    entryEn: "Register quarantine and immigration in advance via Visit Japan Web.", 
    entryUrl: "https://vjw-lp.digital.go.jp/ko/", 
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "cn", 
    name: "중국", 
    nameEn: "China", 
    region: "asia", 
    accent: "#FF9A00", 
    imageUrl: "https://images.unsplash.com/photo-1508197149814-0cc02e8b7f74?q=80&w=800&auto=format&fit=crop",
    capital: "베이징", 
    capitalEn: "Beijing", 
    timezone: "UTC+8", 
    desc: "5000년 역사의 대국", 
    descEn: "Country of 5,000 years of history", 
    weatherIcon: "☀️", 
    weatherSummary: "맑고 건조한 날씨. 20-25도 예상. 자외선 차단제를 챙기세요.", 
    weatherSummaryEn: "Sunny and dry. 20-25°C. Bring sunscreen.", 
    week: [{ d: "월", i: "☀️", t: 24 }, { d: "화", i: "☀️", t: 25 }, { d: "수", i: "☀️", t: 23 }, { d: "목", i: "⛅", t: 22 }, { d: "금", i: "⛅", t: 21 }, { d: "토", i: "☀️", t: 24 }, { d: "일", i: "☀️", t: 25 }], 
    voltage: "220V", 
    voltageType: "Type A/C/I", 
    voltageTypeEn: "Type A/C/I", 
    currency: "위안", 
    currencyEn: "Yuan", 
    currencySymbol: "¥", 
    currencyCode: "CNY", 
    entry: "중국 무비자 15일 입국 가능(2025년 말까지 한시적). 15일 초과 시 비자가 필요합니다.", 
    entryEn: "15 days visa-free entry for Koreans (until end of 2025). Visa required for longer stays.", 
    entryUrl: "https://www.visaforchina.cn/SEL2_KO/",
    visaFree: true, 
    visaDays: "15일", 
    visaDaysEn: "15 Days" 
  },
  { 
    id: "sg", 
    name: "싱가포르", 
    nameEn: "Singapore", 
    region: "asia", 
    accent: "#FF4488", 
    imageUrl: "https://images.unsplash.com/photo-1525625239513-99733285526e?q=80&w=800&auto=format&fit=crop",
    capital: "싱가포르", 
    capitalEn: "Singapore", 
    timezone: "UTC+8", 
    desc: "청결한 도시국가", 
    descEn: "Clean city-state", 
    weatherIcon: "☀️", 
    weatherSummary: "덥고 습한 날씨. 30-33도 예상. 얇은 옷과 물을 충분히 챙기세요.", 
    weatherSummaryEn: "Hot and humid. 30-33°C. Bring light clothes and water.", 
    week: [{ d: "월", i: "☀️", t: 32 }, { d: "화", i: "🌧", t: 30 }, { d: "수", i: "☀️", t: 31 }, { d: "목", i: "🌧", t: 29 }, { d: "금", i: "☀️", t: 32 }, { d: "토", i: "☀️", t: 33 }, { d: "일", i: "⛅", t: 31 }], 
    voltage: "230V", 
    voltageType: "Type G (3-pin)", 
    voltageTypeEn: "Type G (3-pin)", 
    currency: "싱가포르 달러", 
    currencyEn: "Singapore Dollar", 
    currencySymbol: "S$", 
    currencyCode: "SGD", 
    entry: "도착 전 3일 이내에 온라인으로 SG Arrival Card를 등록해야 합니다.", 
    entryEn: "Submit SG Arrival Card online within 3 days prior to arrival.", 
    entryUrl: "https://www.ica.gov.sg/enter-transit-depart/entering-singapore/sg-arrival-card",
    visaFree: true, 
    visaDays: "30일", 
    visaDaysEn: "30 Days" 
  },
  { 
    id: "vn", 
    name: "베트남", 
    nameEn: "Vietnam", 
    region: "asia", 
    accent: "#FF4444", 
    imageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592?q=80&w=800&auto=format&fit=crop",
    capital: "하노이", 
    capitalEn: "Hanoi", 
    timezone: "UTC+7", 
    desc: "동남아의 숨은 보석", 
    descEn: "Hidden gem of Southeast Asia", 
    weatherIcon: "🌧", 
    weatherSummary: "덥고 습하며 소나기가 잦습니다. 28-32도. 우산과 선크림 필수.", 
    weatherSummaryEn: "Hot, humid, frequent showers. 28-32°C. Umbrella and sunscreen required.", 
    week: [{ d: "월", i: "🌧", t: 30 }, { d: "화", i: "🌧", t: 29 }, { d: "수", i: "⛅", t: 31 }, { d: "목", i: "☀️", t: 32 }, { d: "금", i: "🌧", t: 30 }, { d: "토", i: "⛅", t: 31 }, { d: "일", i: "☀️", t: 32 }], 
    voltage: "220V", 
    voltageType: "Type A/C", 
    voltageTypeEn: "Type A/C", 
    currency: "동", 
    currencyEn: "Dong", 
    currencySymbol: "₫", 
    currencyCode: "VND", 
    entry: "45일 무비자 입국 가능. 장기 체류 시 e-Visa 신청이 필요합니다.", 
    entryEn: "45 days visa-free entry. Apply for e-Visa for longer stays.", 
    entryUrl: "https://evisa.xuatnhapcanh.gov.vn/trang-chu-ttdt",
    visaFree: true, 
    visaDays: "45일", 
    visaDaysEn: "45 Days" 
  },
  { 
    id: "th", 
    name: "태국", 
    nameEn: "Thailand", 
    region: "asia", 
    accent: "#00E87A", 
    imageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?q=80&w=800&auto=format&fit=crop",
    capital: "방콕", 
    capitalEn: "Bangkok", 
    timezone: "UTC+7", 
    desc: "미소의 나라", 
    descEn: "Land of Smiles", 
    weatherIcon: "☀️", 
    weatherSummary: "맑고 더운 날씨. 32-36도. 수분 보충을 자주 해주세요.", 
    weatherSummaryEn: "Sunny and hot. 32-36°C. Stay hydrated.", 
    week: [{ d: "월", i: "☀️", t: 34 }, { d: "화", i: "☀️", t: 35 }, { d: "수", i: "☀️", t: 34 }, { d: "목", i: "⛅", t: 33 }, { d: "금", i: "☀️", t: 35 }, { d: "토", i: "☀️", t: 36 }, { d: "일", i: "🌧", t: 32 }], 
    voltage: "220V", 
    voltageType: "Type A/B/C", 
    voltageTypeEn: "Type A/B/C", 
    currency: "바트", 
    currencyEn: "Baht", 
    currencySymbol: "฿", 
    currencyCode: "THB", 
    entry: "한국 여권 소지자는 60일 무비자 입국 가능합니다.", 
    entryEn: "Korean passport holders get 60 days visa-free entry.", 
    entryUrl: "https://www.thaievisa.go.th/",
    visaFree: true, 
    visaDays: "60일", 
    visaDaysEn: "60 Days" 
  },
  { 
    id: "tw", 
    name: "대만", 
    nameEn: "Taiwan", 
    region: "asia", 
    accent: "#00DDAA", 
    imageUrl: "https://images.unsplash.com/photo-1470004914212-05527e49370b?q=80&w=800&auto=format&fit=crop",
    capital: "타이베이", 
    capitalEn: "Taipei", 
    timezone: "UTC+8", 
    desc: "야시장과 미식의 섬", 
    descEn: "Island of food and night markets", 
    weatherIcon: "⛅", 
    weatherSummary: "온화한 날씨. 20-25도. 가볍게 입어도 좋아요.", 
    weatherSummaryEn: "Mild weather. 20-25°C. Light clothing recommended.", 
    week: [{ d: "월", i: "⛅", t: 22 }, { d: "화", i: "☀️", t: 24 }, { d: "수", i: "☀️", t: 25 }, { d: "목", i: "⛅", t: 23 }, { d: "금", i: "🌧", t: 20 }, { d: "토", i: "⛅", t: 22 }, { d: "일", i: "☀️", t: 24 }], 
    voltage: "110V", 
    voltageType: "Type A (2-pin)", 
    currency: "신 타이완 달러", 
    currencyEn: "New Taiwan Dollar", 
    currencySymbol: "NT$", 
    currencyCode: "TWD", 
    entry: "한국 여권 소지자는 90일 무비자 입국이 가능합니다. 입국 전 '온라인 입국신고서(Arrival Card)'를 미리 작성하면 입국 심사가 훨씬 빠르고 간편합니다. (여권 잔여 유효기간 6개월 이상 필수)", 
    entryEn: "90 days visa-free for Korean passport holders. Filling out the 'Online Arrival Card' before arrival makes immigration much faster. (Passport must be valid for at least 6 months)", 
    entryUrl: "https://niaspeedy.immigration.gov.tw/web_msess/",
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "ph", 
    name: "필리핀", 
    nameEn: "Philippines", 
    region: "asia", 
    accent: "#4D9FFF", 
    imageUrl: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?q=80&w=800&auto=format&fit=crop",
    capital: "마닐라", 
    capitalEn: "Manila", 
    timezone: "UTC+8", 
    desc: "7000개 섬의 나라", 
    descEn: "Land of 7,000 islands", 
    weatherIcon: "☀️", 
    weatherSummary: "덥고 습한 날씨. 30-34도. 자외선 주의.", 
    weatherSummaryEn: "Hot and humid. 30-34°C. Warning: High UX.", 
    week: [{ d: "월", i: "☀️", t: 32 }, { d: "화", i: "🌧", t: 30 }, { d: "수", i: "☀️", t: 33 }, { d: "목", i: "☀️", t: 34 }, { d: "금", i: "🌧", t: 30 }, { d: "토", i: "☀️", t: 32 }, { d: "일", i: "☀️", t: 33 }], 
    voltage: "220V", 
    voltageType: "Type A/B/C", 
    voltageTypeEn: "Type A/B/C", 
    currency: "필리핀 페소", 
    currencyEn: "Philippine Peso", 
    currencySymbol: "₱", 
    currencyCode: "PHP", 
    entry: "도착 전 72시간 이내에 eTravel 온라인 등록이 필수입니다.", 
    entryEn: "Mandatory eTravel registration within 72 hours before arrival.", 
    entryUrl: "https://etravel.gov.ph/",
    visaFree: true, 
    visaDays: "30일", 
    visaDaysEn: "30 Days" 
  },
  { 
    id: "id", 
    name: "인도네시아", 
    nameEn: "Indonesia", 
    region: "asia", 
    accent: "#FF5555", 
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?q=80&w=800&auto=format&fit=crop",
    capital: "자카르타", 
    capitalEn: "Jakarta", 
    timezone: "UTC+7", 
    desc: "1만7천 섬의 군도", 
    descEn: "Archipelago of 17,000 islands", 
    weatherIcon: "🌧", 
    weatherSummary: "열대성 기후. 28-33도. 스콜에 대비하세요.", 
    weatherSummaryEn: "Tropical climate. 28-33°C. Prepare for squalls.", 
    week: [{ d: "월", i: "🌧", t: 30 }, { d: "화", i: "☀️", t: 32 }, { d: "수", i: "🌧", t: 29 }, { d: "목", i: "⛅", t: 31 }, { d: "금", i: "☀️", t: 33 }, { d: "토", i: "🌧", t: 30 }, { d: "일", i: "⛅", t: 31 }], 
    voltage: "220V", 
    voltageType: "Type C/F", 
    currency: "루피아", 
    currencyEn: "Rupiah", 
    currencySymbol: "Rp", 
    currencyCode: "IDR", 
    entry: "30일 무비자 입국 가능. 온라인 e-VOA 발급을 권장합니다.", 
    entryEn: "30 days visa-free. e-VOA (Electronic Visa on Arrival) recommended.", 
    entryUrl: "https://evisa.imigrasi.go.id/",
    visaFree: true, 
    visaDays: "30일", 
    visaDaysEn: "30 Days" 
  },
  { 
    id: "my", 
    name: "말레이시아", 
    nameEn: "Malaysia", 
    region: "asia", 
    accent: "#00CC44", 
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?q=80&w=800&auto=format&fit=crop",
    capital: "쿠알라룸푸르", 
    capitalEn: "Kuala Lumpur", 
    timezone: "UTC+8", 
    desc: "다문화 열대 왕국", 
    descEn: "Multicultural tropical kingdom", 
    weatherIcon: "⛅", 
    weatherSummary: "열대성 날씨. 28-32도. 실내 에어컨이 세니 긴팔도 챙기세요.", 
    weatherSummaryEn: "Tropical. 28-32°C. Air conditioning is strong, bring long sleeves.", 
    week: [{ d: "월", i: "☀️", t: 31 }, { d: "화", i: "🌧", t: 29 }, { d: "수", i: "☀️", t: 31 }, { d: "목", i: "🌧", t: 28 }, { d: "금", i: "☀️", t: 30 }, { d: "토", i: "☀️", t: 32 }, { d: "일", i: "⛅", t: 30 }], 
    voltage: "240V", 
    voltageType: "Type G (3-pin)", 
    currency: "링깃", 
    currencyEn: "Ringgit", 
    currencySymbol: "RM", 
    currencyCode: "MYR", 
    entry: "90일 무비자 입국 가능. 입국 전 MDAC(말레이시아 디지털 입국 카드) 필수.", 
    entryEn: "90 days visa-free. Mandatory MDAC (Digital Arrival Card) registration.", 
    entryUrl: "https://imigresen-online.imi.gov.my/mdac/main",
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "hk", 
    name: "홍콩", 
    nameEn: "Hong Kong", 
    region: "asia", 
    accent: "#FF7733", 
    imageUrl: "https://images.unsplash.com/photo-1506354666786-959d6d497f1a?q=80&w=800&auto=format&fit=crop",
    capital: "홍콩", 
    capitalEn: "Hong Kong", 
    timezone: "UTC+8", 
    desc: "동서양이 만나는 도시", 
    descEn: "Where East meets West", 
    weatherIcon: "☀️", 
    weatherSummary: "맑고 온화한 날씨. 22-26도. 쾌적한 날씨입니다.", 
    weatherSummaryEn: "Sunny and mild. 22-26°C. Pleasant weather.", 
    week: [{ d: "월", i: "☀️", t: 24 }, { d: "화", i: "☀️", t: 25 }, { d: "수", i: "⛅", t: 23 }, { d: "목", i: "☀️", t: 26 }, { d: "금", i: "⛅", t: 24 }, { d: "토", i: "☀️", t: 25 }, { d: "일", i: "☀️", t: 26 }], 
    voltage: "220V", 
    voltageType: "Type G (3-pin)", 
    voltageTypeEn: "Type G (3-pin)", 
    currency: "홍콩 달러", 
    currencyEn: "Hong Kong Dollar", 
    currencySymbol: "HK$", 
    currencyCode: "HKD", 
    entry: "90일 무비자 입국 가능. 주홍콩대한민국총영사관에서 정보를 확인하세요.", 
    entryEn: "90 days visa-free entry. Check latest info at Korean Consulate.", 
    entryUrl: "https://overseas.mofa.go.kr/hk-ko/index.do",
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "mn", 
    name: "몽골", 
    nameEn: "Mongolia", 
    region: "asia", 
    accent: "#66AAFF", 
    imageUrl: "https://images.unsplash.com/photo-1526392060635-9d6019884377?q=80&w=800&auto=format&fit=crop",
    capital: "울란바토르", 
    capitalEn: "Ulaanbaatar", 
    timezone: "UTC+8", 
    desc: "푸른 하늘과 초원의 나라", 
    descEn: "Country of blue sky and grasslands", 
    weatherIcon: "☀️", 
    weatherSummary: "건조하고 서늘한 날씨. 10-18도. 일교차가 크니 겉옷을 챙기세요.", 
    weatherSummaryEn: "Dry and cool. 10-18°C. Large temperature range, bring a jacket.", 
    week: [{ d: "월", i: "☀️", t: 15 }, { d: "화", i: "☀️", t: 17 }, { d: "수", i: "⛅", t: 14 }, { d: "목", i: "☀️", t: 16 }, { d: "금", i: "⛅", t: 13 }, { d: "토", i: "☀️", t: 18 }, { d: "일", i: "☀️", t: 16 }], 
    voltage: "220V", 
    voltageType: "Type C/E", 
    currency: "투그릭", 
    currencyEn: "Tugrik", 
    currencySymbol: "₮", 
    currencyCode: "MNT", 
    entry: "30일 무비자 입국 가능. 몽골 외교부 공식 사이트에서 확인하세요.", 
    entryEn: "30 days visa-free entry. Check details at Mongolian Ministry of Foreign Affairs.", 
    entryUrl: "https://evisa.mn/",
    visaFree: true, 
    visaDays: "30일", 
    visaDaysEn: "30 Days" 
  },
  { 
    id: "mo", 
    name: "마카오", 
    nameEn: "Macau", 
    region: "asia", 
    accent: "#00DDBB", 
    imageUrl: "https://images.unsplash.com/photo-1549488344-1f9b8d2bd1f3?q=80&w=800&auto=format&fit=crop",
    capital: "마카오", 
    capitalEn: "Macau", 
    timezone: "UTC+8", 
    desc: "카지노와 포르투갈 감성", 
    descEn: "Casinos and Portuguese vibes", 
    weatherIcon: "⛅", 
    weatherSummary: "맑고 온화한 날씨. 20-26도. 산책하기 좋아요.", 
    weatherSummaryEn: "Sunny and mild. 20-26°C. Good for walking.", 
    week: [{ d: "월", i: "☀️", t: 24 }, { d: "화", i: "☀️", t: 25 }, { d: "수", i: "⛅", t: 23 }, { d: "목", i: "☀️", t: 24 }, { d: "금", i: "☀️", t: 26 }, { d: "토", i: "⛅", t: 24 }, { d: "일", i: "☀️", t: 25 }], 
    voltage: "220V", 
    voltageType: "Type G (3-pin)", 
    currency: "파타카", 
    currencyEn: "Pataca", 
    currencySymbol: "P", 
    currencyCode: "MOP", 
    entry: "90일 무비자 입국 가능. 입국 규정을 미리 확인하세요.", 
    entryEn: "90 days visa-free entry. Please check the entry regulations.", 
    entryUrl: "https://overseas.mofa.go.kr/hk-ko/index.do",
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "in", 
    name: "인도", 
    nameEn: "India", 
    region: "asia", 
    accent: "#FFAA00", 
    imageUrl: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?q=80&w=800&auto=format&fit=crop",
    capital: "뉴델리", 
    capitalEn: "New Delhi", 
    timezone: "UTC+5:30", 
    desc: "신비로운 문명의 나라", 
    descEn: "Land of mysterious civilization", 
    weatherIcon: "☀️", 
    weatherSummary: "덥고 건조한 날씨. 30-40도. 물을 자주 마시세요.", 
    weatherSummaryEn: "Hot and dry. 30-40°C. Drink plenty of water.", 
    week: [{ d: "월", i: "☀️", t: 36 }, { d: "화", i: "☀️", t: 38 }, { d: "수", i: "☀️", t: 37 }, { d: "목", i: "⛅", t: 34 }, { d: "금", i: "☀️", t: 36 }, { d: "토", i: "☀️", t: 39 }, { d: "일", i: "☀️", t: 38 }], 
    voltage: "230V", 
    voltageType: "Type C/D/M", 
    currency: "루피", 
    currencyEn: "Rupee", 
    currencySymbol: "₹", 
    currencyCode: "INR", 
    entry: "인도 e-Visa 신청이 필요합니다. 출발 4일 전까지는 신청을 완료해야 합니다.", 
    entryEn: "Indian e-Visa required. Apply at least 4 days before departure.", 
    entryUrl: "https://indianvisaonline.gov.in/evisa/tvoa.html",
    visaFree: false, 
    visaDays: null 
  },
  { 
    id: "fr", 
    name: "프랑스", 
    nameEn: "France", 
    region: "europe", 
    accent: "#A855F7", 
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=800&auto=format&fit=crop",
    capital: "파리", 
    capitalEn: "Paris", 
    timezone: "UTC+2", 
    desc: "예술과 미식의 나라", 
    descEn: "Land of art and gastronomy", 
    weatherIcon: "⛅", 
    weatherSummary: "맑고 쾌적한 날씨. 16-22도. 파리 산책하기 딱 좋아요.", 
    weatherSummaryEn: "Sunny and pleasant. 16-22°C. Perfect for walking in Paris.", 
    week: [{ d: "월", i: "⛅", t: 18 }, { d: "화", i: "☀️", t: 20 }, { d: "수", i: "☀️", t: 22 }, { d: "목", i: "🌧", t: 17 }, { d: "금", i: "⛅", t: 19 }, { d: "토", i: "☀️", t: 21 }, { d: "일", i: "☀️", t: 20 }], 
    voltage: "230V", 
    voltageType: "Type C/E", 
    currency: "유로", 
    currencyEn: "Euro", 
    currencySymbol: "€", 
    currencyCode: "EUR", 
    entry: "90일 무비자 (솅겐 협정). 주프랑스대한민국대사관 정보를 참고하세요.", 
    entryEn: "90 days visa-free (Schengen). Refer to Korean Embassy in France.", 
    entryUrl: "https://overseas.mofa.go.kr/fr-ko/index.do",
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "de", 
    name: "독일", 
    nameEn: "Germany", 
    region: "europe", 
    accent: "#4D9FFF", 
    imageUrl: "https://images.unsplash.com/photo-1527668752968-14dc70a27c95?q=80&w=800&auto=format&fit=crop",
    capital: "베를린", 
    capitalEn: "Berlin", 
    timezone: "UTC+2", 
    desc: "엔지니어링의 강국", 
    descEn: "Engineering powerhouse", 
    weatherIcon: "⛅", 
    weatherSummary: "서늘하고 흐린 날씨. 12-18도. 우산 챙기세요.", 
    weatherSummaryEn: "Cool and cloudy. 12-18°C. Bring an umbrella.", 
    week: [{ d: "월", i: "🌧", t: 14 }, { d: "화", i: "⛅", t: 16 }, { d: "수", i: "☀️", t: 18 }, { d: "목", i: "⛅", t: 15 }, { d: "금", i: "🌧", t: 13 }, { d: "토", i: "⛅", t: 16 }, { d: "일", i: "☀️", t: 17 }], 
    voltage: "230V", 
    voltageType: "Type C/F", 
    currency: "유로", 
    currencyEn: "Euro", 
    currencySymbol: "€", 
    currencyCode: "EUR", 
    entry: "90일 무비자 (솅겐 협정). 주독일대한민국대사관 정보를 참고하세요.", 
    entryEn: "90 days visa-free (Schengen). Refer to Korean Embassy in Germany.", 
    entryUrl: "https://overseas.mofa.go.kr/de-ko/index.do",
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "it", 
    name: "이탈리아", 
    nameEn: "Italy", 
    region: "europe", 
    accent: "#00C875", 
    imageUrl: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?q=80&w=800&auto=format&fit=crop",
    capital: "로마", 
    capitalEn: "Rome", 
    timezone: "UTC+2", 
    desc: "르네상스의 발상지", 
    descEn: "Birthplace of the Renaissance", 
    weatherIcon: "☀️", 
    weatherSummary: "맑고 따뜻한 날씨. 20-26도. 관광하기 완벽해요.", 
    weatherSummaryEn: "Sunny and warm. 20-26°C. Perfect for sightseeing.", 
    week: [{ d: "월", i: "☀️", t: 22 }, { d: "화", i: "☀️", t: 24 }, { d: "수", i: "⛅", t: 21 }, { d: "목", i: "☀️", t: 23 }, { d: "금", i: "☀️", t: 26 }, { d: "토", i: "⛅", t: 24 }, { d: "일", i: "☀️", t: 25 }], 
    voltage: "230V", 
    voltageType: "Type C/F/L", 
    currency: "유로", 
    currencyEn: "Euro", 
    currencySymbol: "€", 
    currencyCode: "EUR", 
    entry: "90일 무비자 (솅겐 협정). 주이탈리아대한민국대사관 정보를 참고하세요.", 
    entryEn: "90 days visa-free (Schengen). Refer to Korean Embassy in Italy.", 
    entryUrl: "https://overseas.mofa.go.kr/it-ko/index.do",
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "es", 
    name: "스페인", 
    nameEn: "Spain", 
    region: "europe", 
    accent: "#FFA040", 
    imageUrl: "https://images.unsplash.com/photo-1543783207-ec64e4d95325?q=80&w=800&auto=format&fit=crop",
    capital: "마드리드", 
    capitalEn: "Madrid", 
    timezone: "UTC+2", 
    desc: "열정과 플라멩코", 
    descEn: "Passion and Flamenco", 
    weatherIcon: "☀️", 
    weatherSummary: "맑고 더운 날씨. 26-32도. 시에스타 시간엔 실내에서 쉬어요.", 
    weatherSummaryEn: "Sunny and hot. 26-32°C. Rest during siesta.", 
    week: [{ d: "월", i: "☀️", t: 28 }, { d: "화", i: "☀️", t: 30 }, { d: "수", i: "☀️", t: 31 }, { d: "목", i: "⛅", t: 27 }, { d: "금", i: "☀️", t: 29 }, { d: "토", i: "☀️", t: 32 }, { d: "일", i: "☀️", t: 30 }], 
    voltage: "230V", 
    voltageType: "Type C/F", 
    currency: "유로", 
    currencyEn: "Euro", 
    currencySymbol: "€", 
    currencyCode: "EUR", 
    entry: "90일 무비자 (솅겐 협정). 주스페인대한민국대사관 정보를 참고하세요.", 
    entryEn: "90 days visa-free (Schengen). Refer to Korean Embassy in Spain.", 
    entryUrl: "https://overseas.mofa.go.kr/es-ko/index.do",
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "gb", 
    name: "영국", 
    nameEn: "UK", 
    region: "europe", 
    accent: "#CC66FF", 
    imageUrl: "https://images.unsplash.com/photo-1486299267070-83823f5448dd?q=80&w=800&auto=format&fit=crop",
    capital: "런던", 
    capitalEn: "London", 
    timezone: "UTC+1", 
    desc: "전통과 현대의 조화", 
    descEn: "Harmony of tradition and modernity", 
    weatherIcon: "🌧", 
    weatherSummary: "흐리고 쌀쌀한 날씨. 12-18도. 우산은 항상 필수입니다.", 
    weatherSummaryEn: "Cloudy and chilly. 12-18°C. Umbrella is always required.", 
    week: [{ d: "월", i: "🌧", t: 14 }, { d: "화", i: "⛅", t: 15 }, { d: "수", i: "🌧", t: 13 }, { d: "목", i: "⛅", t: 16 }, { d: "금", i: "☀️", t: 17 }, { d: "토", i: "⛅", t: 15 }, { d: "일", i: "🌧", t: 14 }], 
    voltage: "230V", 
    voltageType: "Type G (3-pin)", 
    currency: "파운드", 
    currencyEn: "Pound", 
    currencySymbol: "£", 
    currencyCode: "GBP", 
    entry: "6개월 무비자 입국 가능. 영국 전자여행허가(ETA) 규정을 확인하세요.", 
    entryEn: "6 months visa-free entry. Check UK ETA requirements.", 
    entryUrl: "https://www.gov.uk/check-uk-visa",
    visaFree: true, 
    visaDays: "6개월", 
    visaDaysEn: "6 Months" 
  },
  { 
    id: "nl", 
    name: "네덜란드", 
    nameEn: "Netherlands", 
    region: "europe", 
    accent: "#00AADD", 
    imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=800&auto=format&fit=crop",
    capital: "암스테르담", 
    capitalEn: "Amsterdam", 
    timezone: "UTC+2", 
    desc: "튤립과 풍차의 나라", 
    descEn: "Land of tulips and windmills", 
    weatherIcon: "⛅", 
    weatherSummary: "서늘하고 바람이 불어요. 10-16도. 자전거 여행에 딱이에요.", 
    weatherSummaryEn: "Cool and breezy. 10-16°C. Perfect for cycling.", 
    week: [{ d: "월", i: "⛅", t: 12 }, { d: "화", i: "🌧", t: 11 }, { d: "수", i: "☀️", t: 14 }, { d: "목", i: "⛅", t: 13 }, { d: "금", i: "🌧", t: 11 }, { d: "토", i: "☀️", t: 15 }, { d: "일", i: "⛅", t: 14 }], 
    voltage: "230V", 
    voltageType: "Type C/F", 
    currency: "유로", 
    currencyEn: "Euro", 
    currencySymbol: "€", 
    currencyCode: "EUR", 
    entry: "90일 무비자 (솅겐 협정). 주네덜란드대한민국대사관 정보를 참고하세요.", 
    entryEn: "90 days visa-free (Schengen). Refer to Korean Embassy in Netherlands.", 
    entryUrl: "https://overseas.mofa.go.kr/nl-ko/index.do",
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "pt", 
    name: "포르투갈", 
    nameEn: "Portugal", 
    region: "europe", 
    accent: "#00EE77", 
    imageUrl: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?q=80&w=800&auto=format&fit=crop",
    capital: "리스본", 
    capitalEn: "Lisbon", 
    timezone: "UTC+1", 
    desc: "파두와 대항해의 나라", 
    descEn: "Land of Fado and exploration", 
    weatherIcon: "☀️", 
    weatherSummary: "맑고 온화한 날씨. 18-24도. 리스본 골목 탐방하기 좋아요.", 
    weatherSummaryEn: "Sunny and mild. 18-24°C. Good for exploring Lisbon alleys.", 
    week: [{ d: "월", i: "☀️", t: 21 }, { d: "화", i: "☀️", t: 22 }, { d: "수", i: "⛅", t: 20 }, { d: "목", i: "☀️", t: 23 }, { d: "금", i: "☀️", t: 24 }, { d: "토", i: "⛅", t: 22 }, { d: "일", i: "☀️", t: 21 }], 
    voltage: "230V", 
    voltageType: "Type C/F", 
    currency: "유로", 
    currencyEn: "Euro", 
    currencySymbol: "€", 
    currencyCode: "EUR", 
    entry: "90일 무비자 (솅겐 협정). 주포르투갈대한민국대사관 정보를 참고하세요.", 
    entryEn: "90 days visa-free (Schengen). Refer to Korean Embassy in Portugal.", 
    entryUrl: "https://overseas.mofa.go.kr/pt-ko/index.do",
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "ch", 
    name: "스위스", 
    nameEn: "Switzerland", 
    region: "europe", 
    accent: "#FF3333", 
    imageUrl: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=800&auto=format&fit=crop",
    capital: "베른", 
    capitalEn: "Bern", 
    timezone: "UTC+2", 
    desc: "알프스와 시계의 나라", 
    descEn: "Land of Alps and watches", 
    weatherIcon: "⛅", 
    weatherSummary: "서늘하고 맑은 날씨. 8-15도. 겉옷 필수.", 
    weatherSummaryEn: "Cool and clear. 8-15°C. Jacket required.", 
    week: [{ d: "월", i: "☀️", t: 11 }, { d: "화", i: "⛅", t: 13 }, { d: "수", i: "☀️", t: 15 }, { d: "목", i: "⛅", t: 12 }, { d: "금", i: "🌧", t: 10 }, { d: "토", i: "☀️", t: 14 }, { d: "일", i: "☀️", t: 13 }], 
    voltage: "230V", 
    voltageType: "Type J (3-pin)", 
    currency: "스위스 프랑", 
    currencyEn: "Swiss Franc", 
    currencySymbol: "CHF", 
    currencyCode: "CHF", 
    entry: "90일 무비자 (솅겐 협정). 주스위스대한민국대사관 정보를 참고하세요.", 
    entryEn: "90 days visa-free (Schengen). Refer to Korean Embassy in Switzerland.", 
    entryUrl: "https://overseas.mofa.go.kr/ch-ko/index.do",
    visaFree: true, 
    visaDays: "90일", 
    visaDaysEn: "90 Days" 
  },
  { 
    id: "us", 
    name: "미국", 
    nameEn: "USA", 
    region: "na", 
    accent: "#3399FF", 
    imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=800&auto=format&fit=crop",
    capital: "워싱턴 D.C.", 
    capitalEn: "Washington D.C.", 
    timezone: "UTC-5", 
    desc: "기회의 땅", 
    descEn: "Land of Opportunity", 
    weatherIcon: "🌤", 
    weatherSummary: "뉴욕 기준 15-20도로 쾌적합니다. 도시마다 날씨가 크게 달라요.", 
    weatherSummaryEn: "Mild in NYC (15-20°C). Weather varies by city.", 
    week: [{ d: "월", i: "☀️", t: 18 }, { d: "화", i: "☀️", t: 19 }, { d: "수", i: "⛅", t: 16 }, { d: "목", i: "🌧", t: 14 }, { d: "금", i: "⛅", t: 17 }, { d: "토", i: "☀️", t: 20 }, { d: "일", i: "☀️", t: 19 }], 
    voltage: "120V", 
    voltageType: "Type A/B (2-3pin)", 
    currency: "달러", 
    currencyEn: "Dollar", 
    currencySymbol: "$", 
    currencyCode: "USD", 
    entry: "ESTA 사전 등록 필수. 최소 72시간 전까지는 완료해야 합니다.", 
    entryEn: "ESTA registration required at least 72 hours before departure.", 
    entryUrl: "https://esta.cbp.dhs.gov/",
    visaFree: false, 
    visaDays: null 
  },
  { 
    id: "ca", 
    name: "캐나다", 
    nameEn: "Canada", 
    region: "na", 
    accent: "#FF3333", 
    imageUrl: "https://images.unsplash.com/photo-1503614472-8c9377619280?q=80&w=800&auto=format&fit=crop",
    capital: "오타와", 
    capitalEn: "Ottawa", 
    timezone: "UTC-5", 
    desc: "광활한 자연의 나라", 
    descEn: "Land of vast nature", 
    weatherIcon: "❄️", 
    weatherSummary: "서늘한 날씨. 10-16도. 겉옷 필수.", 
    weatherSummaryEn: "Cool weather. 10-16°C. Jacket required.", 
    week: [{ d: "월", i: "❄️", t: 10 }, { d: "화", i: "⛅", t: 12 }, { d: "수", i: "☀️", t: 14 }, { d: "목", i: "⛅", t: 11 }, { d: "금", i: "🌧", t: 9 }, { d: "토", i: "⛅", t: 13 }, { d: "일", i: "☀️", t: 15 }], 
    voltage: "120V", 
    voltageType: "Type A/B", 
    voltageTypeEn: "Type A/B",
    currency: "캐나다 달러", 
    currencyEn: "Canada Dollar", 
    currencySymbol: "C$", 
    currencyCode: "CAD", 
    entry: "eTA 온라인 신청 필수. 승인 후 입국이 가능합니다.", 
    entryEn: "eTA online application required. Entry allowed after approval.", 
    entryUrl: "https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta/apply.html",
    visaFree: false, 
    visaDays: null,
    visaDaysEn: null
  },
  { 
    id: "mx", 
    name: "멕시코", 
    nameEn: "Mexico", 
    region: "na", 
    accent: "#00CC55", 
    imageUrl: "https://images.unsplash.com/photo-1518105779142-d975f22f1b0a?q=80&w=800&auto=format&fit=crop",
    capital: "멕시코시티", 
    capitalEn: "Mexico City", 
    timezone: "UTC-6", 
    desc: "마야 문명의 후예", 
    descEn: "Descendants of Maya civilization", 
    weatherIcon: "☀️", 
    weatherSummary: "맑고 더운 날씨. 24-30도. 고지대라 자외선이 강해요.", 
    weatherSummaryEn: "Sunny and hot. 24-30°C. Strong UV in highlands.", 
    week: [{ d: "월", i: "☀️", t: 27 }, { d: "화", i: "☀️", t: 28 }, { d: "수", i: "⛅", t: 25 }, { d: "목", i: "🌧", t: 23 }, { d: "금", i: "☀️", t: 26 }, { d: "토", i: "☀️", t: 29 }, { d: "일", i: "☀️", t: 28 }], 
    voltage: "127V", 
    voltageType: "Type A/B", 
    currency: "멕시코 페소", 
    currencyEn: "Mexican Peso", 
    currencySymbol: "$", 
    currencyCode: "MXN", 
    entry: "180일 무비자 입국 가능. 입국 시 FMM(여행 허가증) 작성이 필요할 수 있습니다.", 
    entryEn: "180 days visa-free. FMM registration may be required upon entry.", 
    entryUrl: "https://www.inm.gob.mx/fmme/publico/solicitud.html",
    visaFree: true, 
    visaDays: "180일", 
    visaDaysEn: "180 Days" 
  },
  { 
    id: "au", 
    name: "호주", 
    nameEn: "Australia", 
    region: "oceania", 
    accent: "#00BBDD", 
    imageUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?q=80&w=800&auto=format&fit=crop",
    capital: "캔버라", 
    capitalEn: "Canberra", 
    timezone: "UTC+10", 
    desc: "대자연의 대륙", 
    descEn: "Continent of nature", 
    weatherIcon: "☀️", 
    weatherSummary: "쾌적한 날씨. 18-24도. 야외 활동하기 좋아요.", 
    weatherSummaryEn: "Pleasant. 18-24°C. Great for outdoor activities.", 
    week: [{ d: "월", i: "☀️", t: 22 }, { d: "화", i: "☀️", t: 23 }, { d: "수", i: "⛅", t: 20 }, { d: "목", i: "☀️", t: 21 }, { d: "금", i: "☀️", t: 24 }, { d: "토", i: "⛅", t: 22 }, { d: "일", i: "☀️", t: 23 }], 
    voltage: "230V", 
    voltageType: "Type I (3-pin)", 
    currency: "호주 달러", 
    currencyEn: "Australian Dollar", 
    currencySymbol: "A$", 
    currencyCode: "AUD", 
    entry: "ETA 사전 신청 필수. 'AustralianETA' 앱을 통해 신청을 권장합니다.", 
    entryEn: "Mandatory ETA. Application via 'AustralianETA' app is recommended.", 
    entryUrl: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/electronic-travel-authority-601",
    visaFree: false, 
    visaDays: null 
  },
  { 
    id: "nz", 
    name: "뉴질랜드", 
    nameEn: "New Zealand", 
    region: "oceania", 
    accent: "#8888FF", 
    imageUrl: "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?q=80&w=800&auto=format&fit=crop",
    capital: "웰링턴", 
    capitalEn: "Wellington", 
    timezone: "UTC+12", 
    desc: "반지의 제왕의 고향", 
    descEn: "Home of Lord of the Rings", 
    weatherIcon: "⛅", 
    weatherSummary: "온화한 날씨. 14-20도. 날씨 변화가 잦으니 레이어드 추천.", 
    weatherSummaryEn: "Mild. 14-20°C. Frequent weather changes, layering recommended.", 
    week: [{ d: "월", i: "⛅", t: 16 }, { d: "화", i: "☀️", t: 18 }, { d: "수", i: "🌧", t: 14 }, { d: "목", i: "⛅", t: 15 }, { d: "금", i: "☀️", t: 17 }, { d: "토", i: "⛅", t: 16 }, { d: "일", i: "☀️", t: 19 }], 
    voltage: "230V", 
    voltageType: "Type I (3-pin)", 
    voltageTypeEn: "Type I (3-pin)",
    currency: "뉴질랜드 달러", 
    currencyEn: "New Zealand Dollar", 
    currencySymbol: "NZ$", 
    currencyCode: "NZD", 
    entry: "NZeTA 온라인 신청 필수. 출발 전 승인을 받아야 합니다.", 
    entryEn: "Mandatory NZeTA online application before departure.", 
    entryUrl: "https://nzeta.immigration.govt.nz/",
    visaFree: false, 
    visaDays: null,
    visaDaysEn: null 
  },
];

export const CHECKLIST = [
  { emoji: "⭐", label: "필수", labelEn: "Essential", accent: "#FF4D4D", items: ["여권 (신분증)", "여행자보험", "트래블카드 / 신용카드", "환전 (현지 화폐)", "마스크"], itemsEn: ["Passport (ID)", "Travel Insurance", "Travel Card / Credit Card", "Currency Exchange", "Mask"] },
  { emoji: "🔌", label: "전자기기", labelEn: "Electronics", accent: "#5E5CE6", items: ["변환콘센트 (멀티어댑터)", "노트북 & 거치대", "핸드폰 / 워치 충전기", "멀티탭 (긴 것)", "보조배터리 (기내휴대)", "이어폰 / 비행기 귀마개"], itemsEn: ["Travel Adapter", "Laptop & Stand", "Phone / Watch Charger", "Power Strip", "Power Bank", "Earphones / Earplugs"] },
  { emoji: "👕", label: "의류", labelEn: "Clothing", accent: "#0088FF", items: ["정장 (자켓/바지/셔츠)", "코트 / 스웨터 / 가디건", "얇은패딩 / 바람막이", "내복 / 잠옷 / 실내복", "속옷 / 양말 / 손수건", "장갑 / 목도리 / 귀도리"], itemsEn: ["Suit (Jacket/Pants/Shirt)", "Coat / Sweater / Cardigan", "Light Down / Windbreaker", "Underwear / Pajamas / Lounge", "Underwear / Socks / Handkerchief", "Gloves / Scarf / Earmuffs"] },
  { emoji: "🧼", label: "세면/위생", labelEn: "Toiletries", accent: "#22C55E", items: ["슬리퍼 (기내/호텔용)", "면도기 / 칫솔 / 치약", "치실 / 워터픽", "바디로션 / 얼굴로션", "물티슈 / 휴지", "안경닦이 / 빗", "우산 / 모자 / 핫팩"], itemsEn: ["Slippers", "Razor / Brush / Paste", "Floss / Waterpick", "Body / Face Lotion", "Wipes / Tissue", "Glasses Cloth / Comb", "Umbrella / Hat / Heat Pack"] },
  { emoji: "💊", label: "식량/상비약", labelEn: "Food/Med.", accent: "#F59E0B", items: ["영양제 / 상비약 (타이레놀 등)", "햇반 / 컵라면 / 김치", "말린 국 / 김 / 견과류", "숟가락 / 나무젓가락 / 과일칼", "종이컵 / 위생봉투"], itemsEn: ["Supplements / Medicine", "Instant Rice / Noodles / Kimchi", "Dried Soup / Seaweed / Nuts", "Utensils / Fruit Knife", "Paper Cups / Hygiene Bags"] },
  { emoji: "🎒", label: "기타", labelEn: "Others", accent: "#7D7D8F", items: ["세탁물 봉지 / 키친타올", "에코백 / 여유 가방", "캐리어 내부 사진 찍기"], itemsEn: ["Laundry Bags / Kitchen Towel", "Eco Bag / Extra Bag", "Photo of Luggage Inside"] },
];
