import { CountryInfo, ChecklistItem } from "./types";

export const COUNTRIES: CountryInfo[] = [
  {
    id: "jp",
    name: "일본",
    nameEn: "Japan",
    emoji: "🇯🇵",
    voltage: "100V",
    plugType: "Type A (2-pin)",
    weatherSummary: "현재 대부분 맑음, 낮 기온 18-22도 예상. 야외 활동하기 좋은 날씨입니다.",
    forecast: [
      { day: "월", temp: "21°", condition: "☀️" },
      { day: "화", temp: "22°", condition: "☀️" },
      { day: "수", temp: "19°", condition: "☁️" },
      { day: "목", temp: "18°", condition: "🌧️" },
      { day: "금", temp: "20°", condition: "⛅" },
      { day: "토", temp: "23°", condition: "☀️" },
      { day: "일", temp: "22°", condition: "☀️" },
    ],
    region: 'Asia',
    currency: { symbol: "¥", code: "JPY" }
  },
  {
    id: "us",
    name: "미국",
    nameEn: "USA",
    emoji: "🇺🇸",
    voltage: "120V",
    plugType: "Type A / B",
    weatherSummary: "뉴욕 기준 흐림, 기온 15-20도. 일교차가 크니 가벼운 겉옷을 챙기세요.",
    forecast: [
      { day: "월", temp: "18°", condition: "☁️" },
      { day: "화", temp: "17°", condition: "🌧️" },
      { day: "수", temp: "16°", condition: "🌧️" },
      { day: "목", temp: "19°", condition: "⛅" },
      { day: "금", temp: "21°", condition: "☀️" },
      { day: "토", temp: "22°", condition: "☀️" },
      { day: "일", temp: "20°", condition: "☁️" },
    ],
    region: 'North America',
    currency: { symbol: "$", code: "USD" }
  },
  {
    id: "cn",
    name: "중국",
    nameEn: "China",
    emoji: "🇨🇳",
    voltage: "220V",
    plugType: "Type A / C / I",
    weatherSummary: "베이징 기준 맑음, 기온 20-25도. 대기질 보통. 야외 활동 시 마스크 착용 권장.",
    forecast: [
      { day: "월", temp: "23°", condition: "☀️" },
      { day: "화", temp: "25°", condition: "☀️" },
      { day: "수", temp: "24°", condition: "⛅" },
      { day: "목", temp: "22°", condition: "☁️" },
      { day: "금", temp: "21°", condition: "☀️" },
      { day: "토", temp: "24°", condition: "☀️" },
      { day: "일", temp: "26°", condition: "☀️" },
    ],
    region: 'Asia',
    currency: { symbol: "¥", code: "CNY" }
  },
  {
    id: "sg",
    name: "싱가포르",
    nameEn: "Singapore",
    emoji: "🇸🇬",
    voltage: "230V",
    plugType: "Type G (3-pin)",
    weatherSummary: "열대 기후. 스콜(갑작스런 비) 주의, 기온 28-32도 습도 높음. 항상 우산을 휴대하세요.",
    forecast: [
      { day: "월", temp: "31°", condition: "⛈️" },
      { day: "화", temp: "30°", condition: "⛈️" },
      { day: "수", temp: "32°", condition: "🌦️" },
      { day: "목", temp: "31°", condition: "☀️" },
      { day: "금", temp: "32°", condition: "☀️" },
      { day: "토", temp: "33°", condition: "🌦️" },
      { day: "일", temp: "31°", condition: "⛈️" },
    ],
    region: 'Asia',
    currency: { symbol: "$", code: "SGD" }
  },
  {
    id: "uk",
    name: "영국",
    nameEn: "United Kingdom",
    emoji: "🇬🇧",
    voltage: "230V",
    plugType: "Type G (3-pin)",
    weatherSummary: "런던 기준 흐리고 가끔 비. 기온 12-18도. 변덕스러운 날씨에 대비해 우비나 우산을 준비하세요.",
    forecast: [
      { day: "월", temp: "15°", condition: "☁️" },
      { day: "화", temp: "14°", condition: "🌧️" },
      { day: "수", temp: "16°", condition: "🌦️" },
      { day: "목", temp: "17°", condition: "☁️" },
      { day: "금", temp: "18°", condition: "⛅" },
      { day: "토", temp: "16°", condition: "🌧️" },
      { day: "일", temp: "15°", condition: "☁️" },
    ],
    region: 'Europe',
    currency: { symbol: "£", code: "GBP" }
  },
  {
    id: "de",
    name: "독일",
    nameEn: "Germany",
    emoji: "🇩🇪",
    voltage: "230V",
    plugType: "Type C / F",
    weatherSummary: "대체로 흐리고 비 가능성 있음. 기온 10-15도. 쌀쌀한 날씨이니 따뜻한 옷차림이 필요합니다.",
    forecast: [
      { day: "월", temp: "12°", condition: "☁️" },
      { day: "화", temp: "11°", condition: "🌧️" },
      { day: "수", temp: "13°", condition: "🌧️" },
      { day: "목", temp: "14°", condition: "⛅" },
      { day: "금", temp: "15°", condition: "☀️" },
      { day: "토", temp: "14°", condition: "☁️" },
      { day: "일", temp: "13°", condition: "🌧️" },
    ],
    region: 'Europe',
    currency: { symbol: "€", code: "EUR" }
  },
  {
    id: "fr",
    name: "프랑스",
    nameEn: "France",
    emoji: "🇫🇷",
    voltage: "230V",
    plugType: "Type C / E",
    weatherSummary: "파리 기준 맑음. 기온 15-22도 일교차 주의. 낮에는 따뜻하지만 저녁엔 쌀쌀할 수 있습니다.",
    forecast: [
      { day: "월", temp: "19°", condition: "☀️" },
      { day: "화", temp: "21°", condition: "☀️" },
      { day: "수", temp: "22°", condition: "☀️" },
      { day: "목", temp: "20°", condition: "⛅" },
      { day: "금", temp: "18°", condition: "☁️" },
      { day: "토", temp: "19°", condition: "☀️" },
      { day: "일", temp: "21°", condition: "☀️" },
    ],
    region: 'Europe',
    currency: { symbol: "€", code: "EUR" }
  },
  {
    id: "vn",
    name: "베트남",
    nameEn: "Vietnam",
    emoji: "🇻🇳",
    voltage: "220V",
    plugType: "Type A / C / G",
    weatherSummary: "고온 다습. 하노이 기준 28-32도 습도 높음. 통풍이 잘 되는 옷을 준비하세요.",
    forecast: [
      { day: "월", temp: "30°", condition: "⛅" },
      { day: "화", temp: "31°", condition: "☀️" },
      { day: "수", temp: "32°", condition: "☀️" },
      { day: "목", temp: "30°", condition: "🌦️" },
      { day: "금", temp: "29°", condition: "⛈️" },
      { day: "토", temp: "31°", condition: "☀️" },
      { day: "일", temp: "32°", condition: "☀️" },
    ],
    region: 'Asia',
    currency: { symbol: "₫", code: "VND" }
  },
  {
    id: "th",
    name: "태국",
    nameEn: "Thailand",
    emoji: "🇹🇭",
    voltage: "220V",
    plugType: "Type A / B / C / O",
    weatherSummary: "방콕 기준 무더운 날씨. 기온 30-35도 예상. 자외선이 강하니 선크림과 모자를 챙기세요.",
    forecast: [
      { day: "월", temp: "33°", condition: "☀️" },
      { day: "화", temp: "34°", condition: "☀️" },
      { day: "수", temp: "35°", condition: "☀️" },
      { day: "목", temp: "33°", condition: "⛅" },
      { day: "금", temp: "32°", condition: "🌦️" },
      { day: "토", temp: "34°", condition: "☀️" },
      { day: "일", temp: "35°", condition: "☀️" },
    ],
    region: 'Asia',
    currency: { symbol: "฿", code: "THB" }
  },
  {
    id: "tw",
    name: "대만",
    nameEn: "Taiwan",
    emoji: "🇹🇼",
    voltage: "110V",
    plugType: "Type A / B",
    weatherSummary: "타이베이 기준 흐림. 기온 22-26도. 실내 에어컨이 강할 수 있으니 가벼운 가디건을 추천합니다.",
    forecast: [
      { day: "월", temp: "24°", condition: "☁️" },
      { day: "화", temp: "25°", condition: "☁️" },
      { day: "수", temp: "23°", condition: "🌧️" },
      { day: "목", temp: "22°", condition: "🌧️" },
      { day: "금", temp: "24°", condition: "⛅" },
      { day: "토", temp: "26°", condition: "☀️" },
      { day: "일", temp: "25°", condition: "⛅" },
    ],
    region: 'Asia',
    currency: { symbol: "NT$", code: "TWD" }
  },
  {
    id: "hk",
    name: "홍콩",
    nameEn: "Hong Kong",
    emoji: "🇭🇰",
    voltage: "220V",
    plugType: "Type G (3-pin)",
    weatherSummary: "흐리고 습함. 기온 24-28도. 소나기 가능성이 있으니 우산을 챙기세요.",
    forecast: [
      { day: "월", temp: "26°", condition: "☁️" },
      { day: "화", temp: "27°", condition: "🌦️" },
      { day: "수", temp: "28°", condition: "☀️" },
      { day: "목", temp: "26°", condition: "⛈️" },
      { day: "금", temp: "25°", condition: "🌧️" },
      { day: "토", temp: "27°", condition: "⛅" },
      { day: "일", temp: "28°", condition: "☀️" },
    ],
    region: 'Asia',
    currency: { symbol: "$", code: "HKD" }
  },
  {
    id: "ca",
    name: "캐나다",
    nameEn: "Canada",
    emoji: "🇨🇦",
    voltage: "120V",
    plugType: "Type A / B",
    weatherSummary: "토론토 기준 맑고 쾌적함. 기온 15-22도 예상.",
    forecast: [
      { day: "월", temp: "18°", condition: "☀️" },
      { day: "화", temp: "20°", condition: "☀️" },
      { day: "수", temp: "21°", condition: "⛅" },
      { day: "목", temp: "19°", condition: "☁️" },
      { day: "금", temp: "17°", condition: "🌧️" },
      { day: "토", temp: "19°", condition: "☀️" },
      { day: "일", temp: "21°", condition: "☀️" },
    ],
    region: 'North America',
    currency: { symbol: "$", code: "CAD" }
  },
  {
    id: "au",
    name: "호주",
    nameEn: "Australia",
    emoji: "🇦🇺",
    voltage: "230V",
    plugType: "Type I",
    weatherSummary: "시드니 기준 화창함. 기온 18-24도. 일교차 주의.",
    forecast: [
      { day: "월", temp: "22°", condition: "☀️" },
      { day: "화", temp: "23°", condition: "☀️" },
      { day: "수", temp: "21°", condition: "⛅" },
      { day: "목", temp: "20°", condition: "☁️" },
      { day: "금", temp: "22°", condition: "☀️" },
      { day: "토", temp: "24°", condition: "☀️" },
      { day: "일", temp: "23°", condition: "☀️" },
    ],
    region: 'Oceania',
    currency: { symbol: "$", code: "AUD" }
  },
  {
    id: "ph",
    name: "필리핀",
    nameEn: "Philippines",
    emoji: "🇵🇭",
    voltage: "220V",
    plugType: "Type A / B / C",
    weatherSummary: "마닐라 기준 무덥고 습함. 기온 28-33도. 소나기 잦음.",
    forecast: [
      { day: "월", temp: "31°", condition: "⛈️" },
      { day: "화", temp: "32°", condition: "🌦️" },
      { day: "수", temp: "33°", condition: "☀️" },
      { day: "목", temp: "31°", condition: "⛈️" },
      { day: "금", temp: "30°", condition: "🌧️" },
      { day: "토", temp: "32°", condition: "☀️" },
      { day: "일", temp: "33°", condition: "☀️" },
    ],
    region: 'Asia',
    currency: { symbol: "₱", code: "PHP" }
  },
  {
    id: "id",
    name: "인도네시아",
    nameEn: "Indonesia",
    emoji: "🇮🇩",
    voltage: "230V",
    plugType: "Type C / F",
    weatherSummary: "자카르타 기준 고온다습. 기온 27-32도.",
    forecast: [
      { day: "월", temp: "30°", condition: "🌦️" },
      { day: "화", temp: "31°", condition: "☀️" },
      { day: "수", temp: "32°", condition: "☀️" },
      { day: "목", temp: "30°", condition: "⛈️" },
      { day: "금", temp: "29°", condition: "🌧️" },
      { day: "토", temp: "31°", condition: "☀️" },
      { day: "일", temp: "32°", condition: "☀️" },
    ],
    region: 'Asia',
    currency: { symbol: "Rp", code: "IDR" }
  },
  {
    id: "it",
    name: "이탈리아",
    nameEn: "Italy",
    emoji: "🇮🇹",
    voltage: "230V",
    plugType: "Type C / F / L",
    weatherSummary: "로마 기준 맑고 따뜻함. 기온 18-26도.",
    forecast: [
      { day: "월", temp: "22°", condition: "☀️" },
      { day: "화", temp: "24°", condition: "☀️" },
      { day: "수", temp: "25°", condition: "☀️" },
      { day: "목", temp: "23°", condition: "⛅" },
      { day: "금", temp: "21°", condition: "☁️" },
      { day: "토", temp: "23°", condition: "☀️" },
      { day: "일", temp: "24°", condition: "☀️" },
    ],
    region: 'Europe',
    currency: { symbol: "€", code: "EUR" }
  },
  {
    id: "es",
    name: "스페인",
    nameEn: "Spain",
    emoji: "🇪🇸",
    voltage: "230V",
    plugType: "Type C / F",
    weatherSummary: "마드리드 기준 화창함. 기온 20-28도. 건조함.",
    forecast: [
      { day: "월", temp: "25°", condition: "☀️" },
      { day: "화", temp: "27°", condition: "☀️" },
      { day: "수", temp: "28°", condition: "☀️" },
      { day: "목", temp: "26°", condition: "⛅" },
      { day: "금", temp: "24°", condition: "☀️" },
      { day: "토", temp: "26°", condition: "☀️" },
      { day: "일", temp: "27°", condition: "☀️" },
    ],
    region: 'Europe',
    currency: { symbol: "€", code: "EUR" }
  },
  {
    id: "my",
    name: "말레이시아",
    nameEn: "Malaysia",
    emoji: "🇲🇾",
    voltage: "230V",
    plugType: "Type G (3-pin)",
    weatherSummary: "쿠알라룸푸르 기준 덥고 습함. 기온 27-33도.",
    forecast: [
      { day: "월", temp: "31°", condition: "⛈️" },
      { day: "화", temp: "32°", condition: "🌦️" },
      { day: "수", temp: "33°", condition: "☀️" },
      { day: "목", temp: "32°", condition: "⛈️" },
      { day: "금", temp: "31°", condition: "🌧️" },
      { day: "토", temp: "32°", condition: "☀️" },
      { day: "일", temp: "33°", condition: "☀️" },
    ],
    region: 'Asia',
    currency: { symbol: "RM", code: "MYR" }
  },
  {
    id: "mx",
    name: "멕시코",
    nameEn: "Mexico",
    emoji: "🇲🇽",
    voltage: "127V",
    plugType: "Type A / B",
    weatherSummary: "멕시코시티 기준 맑음. 기온 15-26도. 일교차 및 고산지대 주의.",
    forecast: [
      { day: "월", temp: "22°", condition: "☀️" },
      { day: "화", temp: "24°", condition: "☀️" },
      { day: "수", temp: "25°", condition: "☀️" },
      { day: "목", temp: "23°", condition: "🌤️" },
      { day: "금", temp: "21°", condition: "⛈️" },
      { day: "토", temp: "23°", condition: "☀️" },
      { day: "일", temp: "24°", condition: "☀️" },
    ],
    region: 'North America',
    currency: { symbol: "$", code: "MXN" }
  },
  {
    id: "ch",
    name: "스위스",
    nameEn: "Switzerland",
    emoji: "🇨🇭",
    voltage: "230V",
    plugType: "Type J",
    weatherSummary: "취리히 기준 구름 조금. 기온 8-18도. 산악지대 추위 대비 필수.",
    forecast: [
      { day: "월", temp: "14°", condition: "🌤️" },
      { day: "화", temp: "15°", condition: "☀️" },
      { day: "수", temp: "12°", condition: "☁️" },
      { day: "목", temp: "10°", condition: "🌧️" },
      { day: "금", temp: "13°", condition: "🌤️" },
      { day: "토", temp: "16°", condition: "☀️" },
      { day: "일", temp: "17°", condition: "☀️" },
    ],
    region: 'Europe',
    currency: { symbol: "Fr.", code: "CHF" }
  },
  {
    id: "nl",
    name: "네덜란드",
    nameEn: "Netherlands",
    emoji: "🇳🇱",
    voltage: "230V",
    plugType: "Type C / F",
    weatherSummary: "암스테르담 기준 바람이 강하고 흐림. 기온 10-16도.",
    forecast: [
      { day: "월", temp: "13°", condition: "☁️" },
      { day: "화", temp: "12°", condition: "🌧️" },
      { day: "수", temp: "14°", condition: "🌦️" },
      { day: "목", temp: "15°", condition: "☁️" },
      { day: "금", temp: "14°", condition: "🌤️" },
      { day: "토", temp: "16°", condition: "☀️" },
      { day: "일", temp: "15°", condition: "☁️" },
    ],
    region: 'Europe',
    currency: { symbol: "€", code: "EUR" }
  },
  {
    id: "at",
    name: "오스트리아",
    nameEn: "Austria",
    emoji: "🇦🇹",
    voltage: "230V",
    plugType: "Type C / F",
    weatherSummary: "비엔나 기준 맑고 쾌적. 기온 10-20도.",
    forecast: [
      { day: "월", temp: "18°", condition: "☀️" },
      { day: "화", temp: "19°", condition: "☀️" },
      { day: "수", temp: "17°", condition: "🌤️" },
      { day: "목", temp: "15°", condition: "☁️" },
      { day: "금", temp: "16°", condition: "🌦️" },
      { day: "토", temp: "19°", condition: "☀️" },
      { day: "일", temp: "20°", condition: "☀️" },
    ],
    region: 'Europe',
    currency: { symbol: "€", code: "EUR" }
  },
  {
    id: "se",
    name: "스웨덴",
    nameEn: "Sweden",
    emoji: "🇸🇪",
    voltage: "230V",
    plugType: "Type C / F",
    weatherSummary: "스톡홀름 기준 쌀쌀하고 맑음. 기온 5-14도.",
    forecast: [
      { day: "월", temp: "10°", condition: "☀️" },
      { day: "화", temp: "11°", condition: "🌤️" },
      { day: "수", temp: "9°", condition: "☁️" },
      { day: "목", temp: "8°", condition: "🌧️" },
      { day: "금", temp: "12°", condition: "🌤️" },
      { day: "토", temp: "13°", condition: "☀️" },
      { day: "일", temp: "14°", condition: "☀️" },
    ],
    region: 'Europe',
    currency: { symbol: "kr", code: "SEK" }
  },
  {
    id: "cz",
    name: "체코",
    nameEn: "Czech Republic",
    emoji: "🇨🇿",
    voltage: "230V",
    plugType: "Type E",
    weatherSummary: "프라하 기준 흐리고 가끔 해. 기온 9-18도.",
    forecast: [
      { day: "월", temp: "16°", condition: "🌤️" },
      { day: "화", temp: "17°", condition: "☀️" },
      { day: "수", temp: "15°", condition: "☁️" },
      { day: "목", temp: "13°", condition: "🌧️" },
      { day: "금", temp: "14°", condition: "☁️" },
      { day: "토", temp: "17°", condition: "☀️" },
      { day: "일", temp: "18°", condition: "☀️" },
    ],
    region: 'Europe',
    currency: { symbol: "Kč", code: "CZK" }
  },
  {
    id: "pt",
    name: "포르투갈",
    nameEn: "Portugal",
    emoji: "🇵🇹",
    voltage: "230V",
    plugType: "Type C / F",
    weatherSummary: "리스본 기준 화창하고 온화함. 기온 16-24도.",
    forecast: [
      { day: "월", temp: "22°", condition: "☀️" },
      { day: "화", temp: "23°", condition: "☀️" },
      { day: "수", temp: "24°", condition: "☀️" },
      { day: "목", temp: "21°", condition: "🌤️" },
      { day: "금", temp: "20°", condition: "☁️" },
      { day: "토", temp: "22°", condition: "☀️" },
      { day: "일", temp: "24°", condition: "☀️" },
    ],
    region: 'Europe',
    currency: { symbol: "€", code: "EUR" }
  }
];

export const INITIAL_CHECKLIST: ChecklistItem[] = [
  // 필수
  { id: '1', name: '여권 (신분증)', category: '필수', completed: false, icon: '🛂' },
  { id: '2', name: '여행자보험', category: '필수', completed: false, icon: '📄' },
  { id: '3', name: '트래블카드 / 신용카드', category: '필수', completed: false, icon: '💳' },
  { id: '4', name: '환전 (현지 화폐)', category: '필수', completed: false, icon: '💵' },
  { id: '5', name: '마스크', category: '필수', completed: false, icon: '😷' },
  
  // 전자기기
  { id: '6', name: '변환콘센트 (멀티어댑터)', category: '전자기기', completed: false, icon: '🔌' },
  { id: '7', name: '노트북 & 거치대', category: '전자기기', completed: false, icon: '💻' },
  { id: '8', name: '핸드폰 / 워치 충전기', category: '전자기기', completed: false, icon: '🔋' },
  { id: '9', name: '멀티탭 (긴 것)', category: '전자기기', completed: false, icon: '🔌' },
  { id: '10', name: '보조배터리 (기내휴대)', category: '전자기기', completed: false, icon: '🔋' },
  { id: '11', name: '이어폰 / 비행기 귀마개', category: '전자기기', completed: false, icon: '🎧' },
  
  // 세면/위생
  { id: '12', name: '슬리퍼 (기내/호텔용)', category: '세면/위생', completed: false, icon: '🩴' },
  { id: '13', name: '면도기 / 칫솔 / 치약', category: '세면/위생', completed: false, icon: '🪥' },
  { id: '14', name: '치실 / 워터픽', category: '세면/위생', completed: false, icon: '🦷' },
  { id: '15', name: '바디로션 / 얼굴로션', category: '세면/위생', completed: false, icon: '🧴' },
  { id: '16', name: '물티슈 / 휴지', category: '세면/위생', completed: false, icon: '🧻' },
  { id: '17', name: '안경닦이 / 빗', category: '세면/위생', completed: false, icon: '👓' },
  { id: '18', name: '우산 / 모자 / 핫팩', category: '세면/위생', completed: false, icon: '🌂' },
  
  // 의류
  { id: '19', name: '정장 (자켓/바지/셔츠)', category: '의류', completed: false, icon: '👔' },
  { id: '20', name: '코트 / 스웨터', category: '의류', completed: false, icon: '🧥' },
  { id: '21', name: '얇은패딩 / 바람막이', category: '의류', completed: false, icon: '🧥' },
  { id: '22', name: '내복 / 잠옷 / 실내복', category: '의류', completed: false, icon: '👕' },
  { id: '23', name: '속옷 / 양말 / 손수건', category: '의류', completed: false, icon: '🧦' },
  { id: '24', name: '장갑', category: '의류', completed: false, icon: '🧤' },
  
  // 식량/상비약
  { id: '25', name: '영양제 / 상비약 (타이레놀 등)', category: '식량/상비약', completed: false, icon: '💊' },
  { id: '26', name: '햇반 / 컵라면 / 김치', category: '식량/상비약', completed: false, icon: '🍜' },
  { id: '27', name: '말린 국 / 김 / 견과류', category: '식량/상비약', completed: false, icon: '🥜' },
  { id: '28', name: '숟가락 / 나무젓가락 / 과일칼', category: '식량/상비약', completed: false, icon: '🍴' },
  { id: '29', name: '종이컵 / 위생봉투', category: '식량/상비약', completed: false, icon: '🥤' },
  
  // 기타/가방
  { id: '30', name: '세탁물 봉지 / 키친타올', category: '기타/가방', completed: false, icon: '🧺' },
  { id: '31', name: '에코백 / 여유 가방', category: '기타/가방', completed: false, icon: '👜' },
  { id: '32', name: '캐리어 내부 사진 찍기', category: '기타/가방', completed: false, icon: '📸' },
];
